package com.gios.lightremote

import com.gios.lightremote.proto.Mrp
import com.gios.lightremote.proto.MrpAccumulator
import com.gios.lightremote.proto.ProtoBuf
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The MRP codec against golden protobuf bytes generated by Google's own protobuf via pyatv's
 * generated classes (see `scripts/genvec.py`). This is the whole verification story for the
 * MRP layer: there is no Apple TV in CI, so "does this parse a real SET_STATE" and "is the
 * DEVICE_INFO we send one a device accepts" are both answered by reproducing, byte for byte,
 * what the reference library puts on the wire.
 */
class MrpProtoTest {

    // ------------------------------------------------------------------ parsing

    @Test
    fun `a full SET_STATE yields every now-playing field`() {
        val state = Mrp.parse(Vectors.hex("mrp.set_state_full")) as Mrp.Inbound.State
        assertEquals("Midnight City", state.title)
        assertEquals("M83", state.artist)
        assertEquals("Hurry Up, We're Dreaming", state.album)
        assertEquals(240.0, state.duration)
        assertEquals(63.5, state.elapsed)
        assertEquals(1.0, state.rate)
        assertEquals(Mrp.PlaybackState.Playing, state.playbackState)
        assertNotNull(state.artwork)
        assertEquals(16, state.artwork!!.size)
        assertEquals("image/jpeg", state.artworkMimeType)
    }

    @Test
    fun `a partial SET_STATE carries only the playback state`() {
        val state = Mrp.parse(Vectors.hex("mrp.set_state_paused")) as Mrp.Inbound.State
        assertEquals(Mrp.PlaybackState.Paused, state.playbackState)
        assertNull(state.title)
        assertNull(state.artwork)
    }

    @Test
    fun `SET_NOW_PLAYING_CLIENT names the owning app`() {
        val client = Mrp.parse(Vectors.hex("mrp.set_now_playing_client")) as Mrp.Inbound.Client
        assertEquals("com.spotify.client", client.bundleIdentifier)
        assertEquals("Spotify", client.displayName)
    }

    @Test
    fun `an empty client message means the item went away`() {
        val client = Mrp.parse(Vectors.hex("mrp.set_now_playing_client_empty")) as Mrp.Inbound.Client
        assertNull(client.bundleIdentifier)
    }

    // ------------------------------------------------------------------ the accumulator

    @Test
    fun `the accumulator merges partial updates and keeps the last value`() {
        val acc = MrpAccumulator()
        val playing = acc.apply(Mrp.parse(Vectors.hex("mrp.set_state_full")))
        assertNotNull(playing)
        assertEquals("Midnight City", playing!!.title)
        assertTrue(playing.isPlaying)

        // A state-only flip keeps the title but updates the state.
        val paused = acc.apply(Mrp.parse(Vectors.hex("mrp.set_state_paused")))
        assertNotNull(paused)
        assertEquals("Midnight City", paused!!.title)
        assertEquals(Mrp.PlaybackState.Paused, paused.playbackState)
    }

    @Test
    fun `stopped playback deactivates the snapshot`() {
        val acc = MrpAccumulator()
        acc.apply(Mrp.parse(Vectors.hex("mrp.set_state_full")))
        // Rule from the lock face: stopped must not show a row.
        val stopped = acc.apply(Mrp.parse(Vectors.hex("mrp.set_state_stopped")))
        assertNull(stopped)
    }

    @Test
    fun `an empty now-playing client clears the snapshot`() {
        val acc = MrpAccumulator()
        acc.apply(Mrp.parse(Vectors.hex("mrp.set_state_full")))
        val gone = acc.apply(Mrp.parse(Vectors.hex("mrp.set_now_playing_client_empty")))
        assertNull(gone)
    }

    @Test
    fun `a new item retires the previous artwork`() {
        val acc = MrpAccumulator()
        val first = acc.apply(Mrp.parse(Vectors.hex("mrp.set_state_full")))
        assertNotNull(first!!.artwork)

        // A fresh title with no artwork of its own must not keep the old cover.
        val newItem = Mrp.Inbound.State(
            title = "A Different Song", artist = null, album = null,
            duration = null, elapsed = null, rate = 1.0,
            playbackState = Mrp.PlaybackState.Playing, artwork = null, artworkMimeType = null,
        )
        val second = acc.apply(newItem)
        assertEquals("A Different Song", second!!.title)
        assertNull(second.artwork)
    }

    // ------------------------------------------------------------------ what we send

    /**
     * Compare the inner message we build against pyatv's, field by field, ignoring the
     * envelope's random `uniqueIdentifier` (field 85). Matching the reference client's inner
     * message is the interoperability claim; the random id is not part of it.
     */
    private fun assertInnerMatches(vectorKey: String, extField: Int, ourEnvelope: ByteArray) {
        val reference = ProtoBuf.decode(Vectors.hex(vectorKey))
        val ours = ProtoBuf.decode(ourEnvelope)
        assertEquals(reference.int(1), ours.int(1), "message type differs for $vectorKey")
        val refInner = reference.bytes(extField)
        val ourInner = ours.bytes(extField)
        assertNotNull(refInner, "reference $vectorKey has no field $extField")
        assertNotNull(ourInner, "our message has no field $extField")
        assertTrue(
            refInner!!.contentEquals(ourInner!!),
            "inner message bytes differ for $vectorKey\n ref=${Vectors.encodeHex(refInner)}\n our=${Vectors.encodeHex(ourInner)}",
        )
    }

    @Test
    fun `the DEVICE_INFO we send matches the reference`() {
        assertInnerMatches("mrp.device_info_fields", 20, Mrp.deviceInfo("Light Phone", "AA:BB:CC:DD:EE:01"))
    }

    @Test
    fun `the SET_CONNECTION_STATE we send matches the reference`() {
        assertInnerMatches("mrp.set_connection_state_inner", 42, Mrp.setConnectionState())
    }

    @Test
    fun `the CLIENT_UPDATES_CONFIG we send matches the reference`() {
        assertInnerMatches("mrp.client_updates_config_inner", 21, Mrp.clientUpdatesConfig())
    }

    @Test
    fun `the PLAYBACK_QUEUE_REQUEST we send matches the reference`() {
        assertInnerMatches("mrp.playback_queue_request_inner", 37, Mrp.playbackQueueRequest(0, 512, 512))
    }

    // ------------------------------------------------------------------ codec edge cases

    @Test
    fun `the protobuf codec round-trips varints, fixed widths and nesting`() {
        val nested = ProtoBuf.Writer().string(9, "hi").double(3, 12.5).float(5, 2.0f)
        val message = ProtoBuf.Writer()
            .int(1, 4)
            .bool(13, true)
            .bytes(3, byteArrayOf(1, 2, 3))
            .message(9, nested)
            .toByteArray()
        val decoded = ProtoBuf.decode(message)
        assertEquals(4, decoded.int(1))
        assertEquals(true, decoded.bool(13))
        assertTrue(byteArrayOf(1, 2, 3).contentEquals(decoded.bytes(3)!!))
        val inner = decoded.message(9)!!
        assertEquals("hi", inner.string(9))
        assertEquals(12.5, inner.double(3))
        assertEquals(2.0, inner.float(5))
    }

    @Test
    fun `a malformed message parses as Other rather than throwing`() {
        // A length-delimited field claiming more bytes than exist.
        val bad = byteArrayOf(0x08, 0x04, 0x12, 0x7F)
        assertEquals(Mrp.Inbound.Other, Mrp.parse(bad))
    }
}
