package com.gios.lightremote

import java.util.Properties

/**
 * Golden vectors generated by `scripts/genvec.py` from the very libraries pyatv uses:
 * pyatv's own `opack.py` and `hap_tlv8.py`, `srptools` for SRP, and `cryptography` for
 * HKDF/ChaCha20-Poly1305/Ed25519/X25519.
 *
 * This is the whole verification story for the protocol layer. There is no Apple TV in
 * CI, so "does this handshake work" is answered by reproducing, byte for byte, what a
 * known-working client puts on the wire.
 */
object Vectors {

    private val props: Properties by lazy {
        val stream = Vectors::class.java.getResourceAsStream("/vectors.properties")
            ?: error("vectors.properties missing from test resources")
        Properties().apply { stream.use { load(it) } }
    }

    operator fun get(key: String): String =
        props.getProperty(key) ?: error("no vector named '$key'")

    fun optional(key: String): String? = props.getProperty(key)

    fun count(key: String): Int = get(key).toInt()

    fun names(key: String): List<String> = get(key).split(",").filter { it.isNotEmpty() }

    fun fields(key: String): List<String> = get(key).split("|")

    fun hex(key: String): ByteArray = decodeHex(get(key))

    fun decodeHex(text: String): ByteArray {
        require(text.length % 2 == 0) { "odd-length hex string: $text" }
        val out = ByteArray(text.length / 2)
        for (i in out.indices) {
            out[i] = ((hexDigit(text[i * 2]) shl 4) or hexDigit(text[i * 2 + 1])).toByte()
        }
        return out
    }

    private fun hexDigit(c: Char): Int = when (c) {
        in '0'..'9' -> c - '0'
        in 'a'..'f' -> c - 'a' + 10
        in 'A'..'F' -> c - 'A' + 10
        else -> error("bad hex digit '$c'")
    }

    fun encodeHex(bytes: ByteArray): String =
        bytes.joinToString("") { "%02x".format(it.toInt() and 0xFF) }
}
