#!/usr/bin/env python3
"""
Generate the bottom-bar icons that the light-sdk set has no equivalent for.

Four marks: a D-pad, a trackpad, a 3x3 app grid and a keyboard. Drawn to the same
conventions as the SDK's own `ic_*_white.xml` — 30x30 viewport, white, line art at 2.2
stroke with round caps, small solid shapes where a stroke would close up.

These render at about two grid units, so roughly 24 device pixels on the Light Phone III.
Everything below is sized for that: no detail smaller than 2 units, and no interior gap
narrower than the stroke, or it fills in and the mark turns to mush.

    python3 scripts/generate_ui_icons.py [--preview out.png]

The preview needs Pillow; writing the drawables does not.
"""

from __future__ import annotations

import argparse
import os

CANVAS = 30.0
STROKE = 2.2
RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res", "drawable")


def stroked(path: str, width: float = STROKE) -> str:
    return f"""    <path
        android:pathData="{path}"
        android:fillColor="#00000000"
        android:strokeColor="#FFFFFFFF"
        android:strokeWidth="{width:g}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />"""


def filled(path: str) -> str:
    return f"""    <path
        android:pathData="{path}"
        android:fillColor="#FFFFFFFF" />"""


def vector(name: str, body: list[str]) -> str:
    joined = "\n".join(body)
    return f"""<!--
  Generated by scripts/generate_ui_icons.py — edit the geometry there, not here.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS:g}dp"
    android:height="{CANVAS:g}dp"
    android:viewportWidth="{CANVAS:g}"
    android:viewportHeight="{CANVAS:g}">
{joined}
</vector>
"""


def rect(x0: float, y0: float, x1: float, y1: float) -> str:
    return f"M {x0},{y0} H {x1} V {y1} H {x0} Z"


def rounded_rect(x0: float, y0: float, x1: float, y1: float, r: float) -> str:
    return (
        f"M {x0 + r},{y0} H {x1 - r} "
        f"A {r},{r} 0 0 1 {x1},{y0 + r} V {y1 - r} "
        f"A {r},{r} 0 0 1 {x1 - r},{y1} H {x0 + r} "
        f"A {r},{r} 0 0 1 {x0},{y1 - r} V {y0 + r} "
        f"A {r},{r} 0 0 1 {x0 + r},{y0} Z"
    )


def circle(cx: float, cy: float, r: float) -> str:
    return (
        f"M {cx - r},{cy} A {r},{r} 0 1 0 {cx + r},{cy} "
        f"A {r},{r} 0 1 0 {cx - r},{cy} Z"
    )


# ---------------------------------------------------------------- D-pad
# Four solid triangles around a centre dot. A ring around them was tried and dropped: at
# two grid units the ring and the triangle tips merge into a blob.
DPAD_REACH = 13.0      # tip distance from centre
DPAD_BASE = 8.0        # base distance from centre
DPAD_HALF = 4.2        # half-width of each base
DPAD_DOT = 2.3


def dpad_body() -> list[str]:
    c = CANVAS / 2
    tri = []
    # up, down, left, right
    tri.append(f"M {c},{c - DPAD_REACH} L {c - DPAD_HALF},{c - DPAD_BASE} L {c + DPAD_HALF},{c - DPAD_BASE} Z")
    tri.append(f"M {c},{c + DPAD_REACH} L {c - DPAD_HALF},{c + DPAD_BASE} L {c + DPAD_HALF},{c + DPAD_BASE} Z")
    tri.append(f"M {c - DPAD_REACH},{c} L {c - DPAD_BASE},{c - DPAD_HALF} L {c - DPAD_BASE},{c + DPAD_HALF} Z")
    tri.append(f"M {c + DPAD_REACH},{c} L {c + DPAD_BASE},{c - DPAD_HALF} L {c + DPAD_BASE},{c + DPAD_HALF} Z")
    return [filled(t) for t in tri] + [filled(circle(c, c, DPAD_DOT))]


# ---------------------------------------------------------------- trackpad
# The pad outline with a fingertip and a short trail, so it reads as a surface you drag on
# rather than as an empty box.
PAD_BOX = (4.0, 6.5, 26.0, 23.5)
PAD_RADIUS = 4.0
PAD_DOT = (18.5, 11.8, 2.6)
# A straight trail, not a curved one. The first attempt used a quadratic and at two grid
# units the curl read as the share arrow rather than as a finger being dragged.
PAD_TRAIL = ((10.0, 19.5), (16.2, 13.6))


def trackpad_body() -> list[str]:
    (x0, y0), (x1, y1) = PAD_TRAIL
    return [
        stroked(rounded_rect(*PAD_BOX, PAD_RADIUS)),
        stroked(f"M {x0},{y0} L {x1},{y1}", width=1.9),
        filled(circle(*PAD_DOT)),
    ]


# ---------------------------------------------------------------- app grid
# 3x3 solid squares. Reads as "all the apps" the way a home screen does, which is why the
# dial-pad glyph it replaces was the wrong thing on a remote.
GRID_SIZE = 5.4
GRID_GAP = 3.0


def grid_body() -> list[str]:
    span = 3 * GRID_SIZE + 2 * GRID_GAP
    origin = (CANVAS - span) / 2
    squares = []
    for row in range(3):
        for col in range(3):
            x = origin + col * (GRID_SIZE + GRID_GAP)
            y = origin + row * (GRID_SIZE + GRID_GAP)
            squares.append(filled(rect(x, y, x + GRID_SIZE, y + GRID_SIZE)))
    return squares


# ---------------------------------------------------------------- keyboard
# Case outline, one row of keys, one space bar. Two key rows were tried; at this size the
# rows sit closer together than the stroke is wide and read as a grey band.
KB_BOX = (2.5, 8.5, 27.5, 21.5)
KB_RADIUS = 2.6
KB_KEY_Y = 12.6
KB_KEY_H = 2.2
KB_KEY_W = 2.9
KB_KEY_GAP = 2.0
KB_KEYS = 4
KB_SPACE = (10.0, 17.0, 20.0, 19.2)


def keyboard_body() -> list[str]:
    span = KB_KEYS * KB_KEY_W + (KB_KEYS - 1) * KB_KEY_GAP
    origin = (CANVAS - span) / 2
    keys = []
    for i in range(KB_KEYS):
        x = origin + i * (KB_KEY_W + KB_KEY_GAP)
        keys.append(filled(rect(x, KB_KEY_Y, x + KB_KEY_W, KB_KEY_Y + KB_KEY_H)))
    return [stroked(rounded_rect(*KB_BOX, KB_RADIUS))] + keys + [filled(rect(*KB_SPACE))]


ICONS = {
    "ic_dpad_white": dpad_body,
    "ic_trackpad_white": trackpad_body,
    "ic_apps_grid_white": grid_body,
    "ic_keyboard_white": keyboard_body,
}


def check_bounds() -> None:
    """Nothing may leave the canvas once the stroke is accounted for."""
    edge = STROKE / 2
    assert PAD_BOX[0] - edge >= 0 and PAD_BOX[2] + edge <= CANVAS, "trackpad wider than the canvas"
    assert KB_BOX[0] - edge >= 0 and KB_BOX[2] + edge <= CANVAS, "keyboard wider than the canvas"
    c = CANVAS / 2
    assert c - DPAD_REACH >= 0 and c + DPAD_REACH <= CANVAS, "D-pad triangles escape the canvas"
    # The space bar has to clear the case outline.
    assert KB_SPACE[3] + edge < KB_BOX[3], "space bar overlaps the keyboard case"
    # Keys must not touch the case either.
    assert KB_KEY_Y - edge > KB_BOX[1], "key row overlaps the keyboard case"
    span = 3 * GRID_SIZE + 2 * GRID_GAP
    assert span < CANVAS, "app grid wider than the canvas"


def write_icons() -> None:
    os.makedirs(RES, exist_ok=True)
    for name, body in ICONS.items():
        with open(os.path.join(RES, f"{name}.xml"), "w") as fh:
            fh.write(vector(name, body()))


def write_preview(path: str) -> None:
    """Render the four marks at the size they are actually used, plus a 4x blow-up."""
    from PIL import Image, ImageDraw

    s = 16
    small = 24  # about what two grid units comes to on the LP3
    tiles = []
    for name, body in ICONS.items():
        img = Image.new("RGB", (int(CANVAS * s), int(CANVAS * s)), (0, 0, 0))
        d = ImageDraw.Draw(img)
        _draw(d, name, s)
        tiles.append((name, img))

    sheet = Image.new("RGB", (len(tiles) * 110, 150), (0, 0, 0))
    for i, (_, img) in enumerate(tiles):
        sheet.paste(img.resize((96, 96), Image.LANCZOS), (i * 110 + 7, 8))
        sheet.paste(img.resize((small, small), Image.LANCZOS), (i * 110 + 43, 112))
    sheet.save(path)


def _draw(d, name: str, s: int) -> None:
    """Mirror of the vector geometry, for the preview only."""
    white = (255, 255, 255)
    c = CANVAS / 2 * s
    if name == "ic_dpad_white":
        for pts in (
            [(c, c - DPAD_REACH * s), (c - DPAD_HALF * s, c - DPAD_BASE * s), (c + DPAD_HALF * s, c - DPAD_BASE * s)],
            [(c, c + DPAD_REACH * s), (c - DPAD_HALF * s, c + DPAD_BASE * s), (c + DPAD_HALF * s, c + DPAD_BASE * s)],
            [(c - DPAD_REACH * s, c), (c - DPAD_BASE * s, c - DPAD_HALF * s), (c - DPAD_BASE * s, c + DPAD_HALF * s)],
            [(c + DPAD_REACH * s, c), (c + DPAD_BASE * s, c - DPAD_HALF * s), (c + DPAD_BASE * s, c + DPAD_HALF * s)],
        ):
            d.polygon(pts, fill=white)
        r = DPAD_DOT * s
        d.ellipse([c - r, c - r, c + r, c + r], fill=white)
    elif name == "ic_trackpad_white":
        x0, y0, x1, y1 = (v * s for v in PAD_BOX)
        d.rounded_rectangle([x0, y0, x1, y1], radius=PAD_RADIUS * s, outline=white, width=int(STROKE * s))
        (tx0, ty0), (tx1, ty1) = PAD_TRAIL
        d.line([tx0 * s, ty0 * s, tx1 * s, ty1 * s], fill=white, width=int(1.9 * s))
        cx, cy, r = (v * s for v in PAD_DOT)
        d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=white)
    elif name == "ic_apps_grid_white":
        span = 3 * GRID_SIZE + 2 * GRID_GAP
        o = (CANVAS - span) / 2
        for row in range(3):
            for col in range(3):
                x = (o + col * (GRID_SIZE + GRID_GAP)) * s
                y = (o + row * (GRID_SIZE + GRID_GAP)) * s
                d.rectangle([x, y, x + GRID_SIZE * s, y + GRID_SIZE * s], fill=white)
    elif name == "ic_keyboard_white":
        x0, y0, x1, y1 = (v * s for v in KB_BOX)
        d.rounded_rectangle([x0, y0, x1, y1], radius=KB_RADIUS * s, outline=white, width=int(STROKE * s))
        span = KB_KEYS * KB_KEY_W + (KB_KEYS - 1) * KB_KEY_GAP
        o = (CANVAS - span) / 2
        for i in range(KB_KEYS):
            x = (o + i * (KB_KEY_W + KB_KEY_GAP)) * s
            d.rectangle([x, KB_KEY_Y * s, x + KB_KEY_W * s, (KB_KEY_Y + KB_KEY_H) * s], fill=white)
        a, b, cc, dd = (v * s for v in KB_SPACE)
        d.rectangle([a, b, cc, dd], fill=white)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", help="also write a PNG contact sheet here")
    args = parser.parse_args()

    check_bounds()
    write_icons()
    if args.preview:
        write_preview(args.preview)
    print("wrote", ", ".join(ICONS), "to", os.path.normpath(RES))
