#!/usr/bin/env python3
"""
Regenerate the LightRemote launcher icon.

The mark is a remote drawn as line art — tall rounded body, hollow clickpad ring in the
upper half, one filled button below — white on black, matching the icon language of the
sibling Light Phone III tools.

Geometry is defined once, in the 108x108 adaptive-icon canvas, and emitted twice: as
Android vector paths and as raster fallbacks. Everything sits inside the 18..90 safe zone
so no launcher mask can clip it.

    python3 scripts/generate_icon.py

Needs Pillow. Rewrites app/src/main/res/{drawable,mipmap-*}.
"""

from __future__ import annotations

import os

from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

CANVAS = 108
SAFE = (18, 90)
STROKE = 5.0

# Body: a tall rounded rectangle, centreline coordinates. Narrow enough to read as a
# remote rather than a phone.
BODY = (36.0, 21.0, 72.0, 87.0)  # left, top, right, bottom
BODY_R = 13.0

# Clickpad: hollow ring in the upper half, the visual centre of the mark.
RING_C = (54.0, 42.0)
RING_R = 8.5

# One button below it. Filled, so the mark has a single solid anchor.
DOT_C = (54.0, 66.0)
DOT_R = 3.5

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8


def check_safe_zone() -> None:
    lo, hi = SAFE
    edge = STROKE / 2
    left, top, right, bottom = BODY
    extents = [
        (left - edge, top - edge),
        (right + edge, bottom + edge),
        (RING_C[0] - RING_R - edge, RING_C[1] - RING_R - edge),
        (RING_C[0] + RING_R + edge, RING_C[1] + RING_R + edge),
        (DOT_C[0], DOT_C[1] + DOT_R),
    ]
    for x, y in extents:
        assert lo <= x <= hi and lo <= y <= hi, f"({x}, {y}) escapes the safe zone"
    # The ring has to sit clear of the body outline or the two strokes merge into a blob.
    clearance = 2.0
    assert left + edge + clearance < RING_C[0] - RING_R - edge, "ring touches the body"
    assert RING_C[0] + RING_R + edge < right - edge - clearance, "ring touches the body"
    assert RING_C[1] + RING_R < DOT_C[1] - DOT_R - 4, "ring and button are too close"


def body_path() -> str:
    left, top, right, bottom = BODY
    r = BODY_R
    return (
        f"M {left + r},{top} H {right - r} "
        f"A {r},{r} 0 0 1 {right},{top + r} V {bottom - r} "
        f"A {r},{r} 0 0 1 {right - r},{bottom} H {left + r} "
        f"A {r},{r} 0 0 1 {left},{bottom - r} V {top + r} "
        f"A {r},{r} 0 0 1 {left + r},{top} Z"
    )


def circle_path(centre: tuple[float, float], radius: float) -> str:
    cx, cy = centre
    return (
        f"M {cx - radius},{cy} A {radius},{radius} 0 1 0 {cx + radius},{cy} "
        f"A {radius},{radius} 0 1 0 {cx - radius},{cy} Z"
    )


def write_vectors() -> None:
    background = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Pure black. On the Light Phone III's OLED these pixels are simply off. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h{CANVAS}v{CANVAS}h-{CANVAS}z" />
</vector>
"""

    def stroked(path: str) -> str:
        return f"""    <path
        android:pathData="{path}"
        android:fillColor="#00000000"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="{STROKE:g}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />"""

    def filled(path: str) -> str:
        return f"""    <path
        android:pathData="{path}"
        android:fillColor="#FFFFFF" />"""

    foreground = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by scripts/generate_icon.py — edit the geometry there, not here.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
{stroked(body_path())}
{stroked(circle_path(RING_C, RING_R))}
{filled(circle_path(DOT_C, DOT_R))}
</vector>
"""

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    os.makedirs(os.path.join(RES, "mipmap-anydpi-v26"), exist_ok=True)
    with open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w") as f:
        f.write(background)
    with open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground)
    for name in ("ic_launcher", "ic_launcher_round"):
        with open(os.path.join(RES, "mipmap-anydpi-v26", f"{name}.xml"), "w") as f:
            f.write(adaptive)


def render(px: int, circular: bool) -> Image.Image:
    s = SUPERSAMPLE
    white = (255, 255, 255, 255)
    img = Image.new("RGBA", (CANVAS * s, CANVAS * s), (0, 0, 0, 255))
    d = ImageDraw.Draw(img)
    w = int(STROKE * s)

    left, top, right, bottom = (v * s for v in BODY)
    d.rounded_rectangle([left, top, right, bottom], radius=BODY_R * s, outline=white, width=w)

    cx, cy = (v * s for v in RING_C)
    r = RING_R * s
    d.ellipse([cx - r, cy - r, cx + r, cy + r], outline=white, width=w)

    dx, dy = (v * s for v in DOT_C)
    dr = DOT_R * s
    d.ellipse([dx - dr, dy - dr, dx + dr, dy + dr], fill=white)

    # Crop to the 72x72 the launcher actually shows, so the legacy raster matches what the
    # adaptive icon looks like under a mask.
    lo, hi = SAFE
    out = img.crop((lo * s, lo * s, hi * s, hi * s)).resize((px, px), Image.LANCZOS)

    if circular:
        mask = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(mask).ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
        mask = mask.resize((px, px), Image.LANCZOS)
        base = Image.new("RGBA", (px, px), (0, 0, 0, 0))
        base.paste(out, (0, 0), mask)
        out = base
    return out


def write_rasters() -> None:
    for density, px in DENSITIES.items():
        folder = os.path.join(RES, f"mipmap-{density}")
        os.makedirs(folder, exist_ok=True)
        render(px, circular=False).save(os.path.join(folder, "ic_launcher.png"))
        render(px, circular=True).save(os.path.join(folder, "ic_launcher_round.png"))


if __name__ == "__main__":
    check_safe_zone()
    write_vectors()
    write_rasters()
    print("icon written to", os.path.normpath(RES))
