#!/usr/bin/env python3
"""
Generate the bottom-bar icons that the light-sdk set has no equivalent for.

Four marks: a D-pad, a trackpad, a 3x3 app grid and a keyboard. Drawn to the same
conventions as the SDK's own `ic_*_white.xml` — 30x30 viewport, white, line art at 2.2
stroke with round caps, small solid shapes where a stroke would close up.

These render at about two grid units, so roughly 24 device pixels on the Light Phone III.
Everything below is sized for that: no detail smaller than 2 units, and no interior gap
narrower than the stroke, or it fills in and the mark turns to mush.

    python3 scripts/generate_ui_icons.py [--preview out.png]

The preview needs Pillow; writing the drawables does not.
"""

from __future__ import annotations

import argparse
import os

CANVAS = 30.0
STROKE = 2.2
RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res", "drawable")


def stroked(path: str, width: float = STROKE) -> str:
    return f"""    <path
        android:pathData="{path}"
        android:fillColor="#00000000"
        android:strokeColor="#FFFFFFFF"
        android:strokeWidth="{width:g}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />"""


def filled(path: str) -> str:
    return f"""    <path
        android:pathData="{path}"
        android:fillColor="#FFFFFFFF" />"""


def vector(name: str, body: list[str]) -> str:
    joined = "\n".join(body)
    return f"""<!--
  Generated by scripts/generate_ui_icons.py — edit the geometry there, not here.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS:g}dp"
    android:height="{CANVAS:g}dp"
    android:viewportWidth="{CANVAS:g}"
    android:viewportHeight="{CANVAS:g}">
{joined}
</vector>
"""


def rect(x0: float, y0: float, x1: float, y1: float) -> str:
    return f"M {x0},{y0} H {x1} V {y1} H {x0} Z"


def rounded_rect(x0: float, y0: float, x1: float, y1: float, r: float) -> str:
    return (
        f"M {x0 + r},{y0} H {x1 - r} "
        f"A {r},{r} 0 0 1 {x1},{y0 + r} V {y1 - r} "
        f"A {r},{r} 0 0 1 {x1 - r},{y1} H {x0 + r} "
        f"A {r},{r} 0 0 1 {x0},{y1 - r} V {y0 + r} "
        f"A {r},{r} 0 0 1 {x0 + r},{y0} Z"
    )


def circle(cx: float, cy: float, r: float) -> str:
    return (
        f"M {cx - r},{cy} A {r},{r} 0 1 0 {cx + r},{cy} "
        f"A {r},{r} 0 1 0 {cx - r},{cy} Z"
    )


# ---------------------------------------------------------------- D-pad
# Four solid triangles around a centre dot. A ring around them was tried and dropped: at
# two grid units the ring and the triangle tips merge into a blob.
DPAD_REACH = 13.0      # tip distance from centre
DPAD_BASE = 8.0        # base distance from centre
DPAD_HALF = 4.2        # half-width of each base
DPAD_DOT = 2.3


def dpad_body() -> list[str]:
    c = CANVAS / 2
    tri = []
    # up, down, left, right
    tri.append(f"M {c},{c - DPAD_REACH} L {c - DPAD_HALF},{c - DPAD_BASE} L {c + DPAD_HALF},{c - DPAD_BASE} Z")
    tri.append(f"M {c},{c + DPAD_REACH} L {c - DPAD_HALF},{c + DPAD_BASE} L {c + DPAD_HALF},{c + DPAD_BASE} Z")
    tri.append(f"M {c - DPAD_REACH},{c} L {c - DPAD_BASE},{c - DPAD_HALF} L {c - DPAD_BASE},{c + DPAD_HALF} Z")
    tri.append(f"M {c + DPAD_REACH},{c} L {c + DPAD_BASE},{c - DPAD_HALF} L {c + DPAD_BASE},{c + DPAD_HALF} Z")
    return [filled(t) for t in tri] + [filled(circle(c, c, DPAD_DOT))]


# ---------------------------------------------------------------- trackpad
# The pad outline with a fingertip and a short trail, so it reads as a surface you drag on
# rather than as an empty box.
PAD_BOX = (3.5, 6.0, 26.5, 24.0)
PAD_RADIUS = 4.5


def trackpad_body() -> list[str]:
    # Just the outline. It carried a fingertip and a drag trail; both went, because next to a
    # keyboard and an app grid the empty pad is already the odd one out, and whatever sits
    # inside it at two grid units competes with the border instead of explaining it.
    return [stroked(rounded_rect(*PAD_BOX, PAD_RADIUS))]


# ---------------------------------------------------------------- app grid
# 3x3 solid squares. Reads as "all the apps" the way a home screen does, which is why the
# dial-pad glyph it replaces was the wrong thing on a remote.
GRID_SIZE = 5.4
GRID_GAP = 3.0


def grid_body() -> list[str]:
    span = 3 * GRID_SIZE + 2 * GRID_GAP
    origin = (CANVAS - span) / 2
    squares = []
    for row in range(3):
        for col in range(3):
            x = origin + col * (GRID_SIZE + GRID_GAP)
            y = origin + row * (GRID_SIZE + GRID_GAP)
            squares.append(filled(rect(x, y, x + GRID_SIZE, y + GRID_SIZE)))
    return squares


# ---------------------------------------------------------------- keyboard
# Case outline, two rows of keys, a space bar.
#
# One row plus a space bar came first and read as a card or a wallet at two grid units — the
# second row is what makes it unmistakably a keyboard. Rows of bare keys with no case were
# tried too (which is what Apple's own glyph does) and blurred into a smudge at this size;
# the case is doing real work as an outline around them.
KB_BOX = (2.0, 8.0, 28.0, 22.0)
KB_RADIUS = 2.6
KB_FIRST_ROW_Y = 11.4
KB_KEY_H = 2.0
KB_KEY_W = 2.4
KB_KEY_GAP = 2.0
KB_ROW_GAP = 1.6
KB_ROWS = (5, 4)          # keys per row, top to bottom
KB_SPACE_W = 9.0


def _key_row(count: float, width: float, y: float) -> list[str]:
    span = count * width + (count - 1) * KB_KEY_GAP
    origin = (CANVAS - span) / 2
    return [
        filled(rect(origin + i * (width + KB_KEY_GAP), y, origin + i * (width + KB_KEY_GAP) + width, y + KB_KEY_H))
        for i in range(int(count))
    ]


def _row_y(index: int) -> float:
    return KB_FIRST_ROW_Y + index * (KB_KEY_H + KB_ROW_GAP)


def keyboard_body() -> list[str]:
    body = [stroked(rounded_rect(*KB_BOX, KB_RADIUS))]
    for i, count in enumerate(KB_ROWS):
        body += _key_row(count, KB_KEY_W, _row_y(i))
    space_y = _row_y(len(KB_ROWS))
    origin = (CANVAS - KB_SPACE_W) / 2
    body.append(filled(rect(origin, space_y, origin + KB_SPACE_W, space_y + KB_KEY_H)))
    return body


# ---------------------------------------------------------------- home
# House outline: roof over a box. The SDK has no home mark at all, and a house is the one
# glyph nobody has to learn.
# Overhang is what decides whether this is a house or an up arrow. At 3.5 either side the
# roof outruns the walls and the eye reads a chevron on a stick; 2 keeps it a house.
HOME_ROOF = ((5.5, 15.0), (15.0, 7.0), (24.5, 15.0))
HOME_BODY = (7.5, 14.5, 22.5, 24.0)


def home_body() -> list[str]:
    (ax, ay), (bx, by), (cx, cy) = HOME_ROOF
    return [
        stroked(f"M {ax},{ay} L {bx},{by} L {cx},{cy}"),
        # Open at the top: the roof already closes it, and drawing the lid as well leaves a
        # double-thick line across the middle of the house.
        stroked(
            f"M {HOME_BODY[0]},{HOME_BODY[1]} V {HOME_BODY[3]} "
            f"H {HOME_BODY[2]} V {HOME_BODY[1]}"
        ),
    ]


# ---------------------------------------------------------------- more
# Three dots. The drawer behind it holds playback, the pad toggle, apps and the keyboard —
# too mixed a bag for any one picture, and an ellipsis is what everybody already reads as
# "the rest of it".
MORE_DOTS_X = (8.0, 15.0, 22.0)
MORE_DOT_Y = 15.0
MORE_DOT_R = 2.4


def more_body() -> list[str]:
    return [filled(circle(x, MORE_DOT_Y, MORE_DOT_R)) for x in MORE_DOTS_X]


ICONS = {
    "ic_dpad_white": dpad_body,
    "ic_trackpad_white": trackpad_body,
    "ic_apps_grid_white": grid_body,
    "ic_keyboard_white": keyboard_body,
    "ic_home_white": home_body,
    "ic_more_white": more_body,
}


def check_bounds() -> None:
    """Nothing may leave the canvas once the stroke is accounted for."""
    edge = STROKE / 2
    assert PAD_BOX[0] - edge >= 0 and PAD_BOX[2] + edge <= CANVAS, "trackpad wider than the canvas"
    assert KB_BOX[0] - edge >= 0 and KB_BOX[2] + edge <= CANVAS, "keyboard wider than the canvas"
    c = CANVAS / 2
    assert c - DPAD_REACH >= 0 and c + DPAD_REACH <= CANVAS, "D-pad triangles escape the canvas"
    # Every key row, and the space bar, has to sit clear of the case outline.
    assert KB_FIRST_ROW_Y - edge > KB_BOX[1], "top key row overlaps the keyboard case"
    last = _row_y(len(KB_ROWS)) + KB_KEY_H
    assert last + edge < KB_BOX[3], "space bar overlaps the keyboard case"
    # And the rows must not merge: a gap narrower than the key height reads as a solid band.
    assert KB_ROW_GAP >= KB_KEY_H * 0.75, "key rows too close to stay separate"
    widest = max(KB_ROWS) * KB_KEY_W + (max(KB_ROWS) - 1) * KB_KEY_GAP
    assert widest + 2 * edge < KB_BOX[2] - KB_BOX[0], "key row wider than the keyboard case"
    span = 3 * GRID_SIZE + 2 * GRID_GAP
    assert span < CANVAS, "app grid wider than the canvas"


def write_icons() -> None:
    os.makedirs(RES, exist_ok=True)
    for name, body in ICONS.items():
        with open(os.path.join(RES, f"{name}.xml"), "w") as fh:
            fh.write(vector(name, body()))


def write_preview(path: str) -> None:
    """Render the four marks at the size they are actually used, plus a 4x blow-up."""
    from PIL import Image, ImageDraw

    s = 16
    small = 24  # about what two grid units comes to on the LP3
    tiles = []
    for name, body in ICONS.items():
        img = Image.new("RGB", (int(CANVAS * s), int(CANVAS * s)), (0, 0, 0))
        d = ImageDraw.Draw(img)
        _draw(d, name, s)
        tiles.append((name, img))

    sheet = Image.new("RGB", (len(tiles) * 110, 150), (0, 0, 0))
    for i, (_, img) in enumerate(tiles):
        sheet.paste(img.resize((96, 96), Image.LANCZOS), (i * 110 + 7, 8))
        sheet.paste(img.resize((small, small), Image.LANCZOS), (i * 110 + 43, 112))
    sheet.save(path)


def _draw(d, name: str, s: int) -> None:
    """Mirror of the vector geometry, for the preview only."""
    white = (255, 255, 255)
    c = CANVAS / 2 * s
    if name == "ic_dpad_white":
        for pts in (
            [(c, c - DPAD_REACH * s), (c - DPAD_HALF * s, c - DPAD_BASE * s), (c + DPAD_HALF * s, c - DPAD_BASE * s)],
            [(c, c + DPAD_REACH * s), (c - DPAD_HALF * s, c + DPAD_BASE * s), (c + DPAD_HALF * s, c + DPAD_BASE * s)],
            [(c - DPAD_REACH * s, c), (c - DPAD_BASE * s, c - DPAD_HALF * s), (c - DPAD_BASE * s, c + DPAD_HALF * s)],
            [(c + DPAD_REACH * s, c), (c + DPAD_BASE * s, c - DPAD_HALF * s), (c + DPAD_BASE * s, c + DPAD_HALF * s)],
        ):
            d.polygon(pts, fill=white)
        r = DPAD_DOT * s
        d.ellipse([c - r, c - r, c + r, c + r], fill=white)
    elif name == "ic_trackpad_white":
        x0, y0, x1, y1 = (v * s for v in PAD_BOX)
        d.rounded_rectangle([x0, y0, x1, y1], radius=PAD_RADIUS * s, outline=white, width=int(STROKE * s))
    elif name == "ic_apps_grid_white":
        span = 3 * GRID_SIZE + 2 * GRID_GAP
        o = (CANVAS - span) / 2
        for row in range(3):
            for col in range(3):
                x = (o + col * (GRID_SIZE + GRID_GAP)) * s
                y = (o + row * (GRID_SIZE + GRID_GAP)) * s
                d.rectangle([x, y, x + GRID_SIZE * s, y + GRID_SIZE * s], fill=white)
    elif name == "ic_keyboard_white":
        x0, y0, x1, y1 = (v * s for v in KB_BOX)
        d.rounded_rectangle([x0, y0, x1, y1], radius=KB_RADIUS * s, outline=white, width=int(STROKE * s))
        for row, count in enumerate(KB_ROWS):
            span = count * KB_KEY_W + (count - 1) * KB_KEY_GAP
            o = (CANVAS - span) / 2
            y = _row_y(row)
            for i in range(count):
                x = (o + i * (KB_KEY_W + KB_KEY_GAP)) * s
                d.rectangle([x, y * s, x + KB_KEY_W * s, (y + KB_KEY_H) * s], fill=white)
        space_y = _row_y(len(KB_ROWS))
        o = (CANVAS - KB_SPACE_W) / 2
        d.rectangle([o * s, space_y * s, (o + KB_SPACE_W) * s, (space_y + KB_KEY_H) * s], fill=white)
    elif name == "ic_home_white":
        pts = [(x * s, y * s) for x, y in HOME_ROOF]
        d.line(pts, fill=white, width=int(STROKE * s), joint="curve")
        x0, y0, x1, y1 = (v * s for v in HOME_BODY)
        d.line([(x0, y0), (x0, y1), (x1, y1), (x1, y0)], fill=white, width=int(STROKE * s), joint="curve")
    elif name == "ic_more_white":
        r = MORE_DOT_R * s
        for x in MORE_DOTS_X:
            cx, cy = x * s, MORE_DOT_Y * s
            d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=white)
    else:
        # Loud on purpose. The preview is the only place these get judged, and an icon with
        # no branch here renders as an empty tile that looks like a design decision.
        raise AssertionError(f"no preview mirror for {name}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", help="also write a PNG contact sheet here")
    args = parser.parse_args()

    check_bounds()
    write_icons()
    if args.preview:
        write_preview(args.preview)
    print("wrote", ", ".join(ICONS), "to", os.path.normpath(RES))
